server:
  port: 8084

spring:
  application:
    name: cart
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: "jdbc:mysql://3.34.177.168/cart"
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# swagger ?? ??
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true
tag:
  version: 1.0.0

# MSA 서버 설정
service:
  member:
    url: "http://snowball-class.shop:30001"
  lesson:
    url: "http://snowball-class.shop:30002"
  payment:
    url: "http://snowball-class.shop:30003"
  cart:
    url: "http://snowball-class.shop:30004"